"""Component ablation (variable importance).

Quantifies how much each pipeline component contributes to skill by removing it
and measuring the change in KGE / PBIAS against BR-DWGD over the 17 sites
(1991-2020). Reported as Delta vs the full baseline, so any small absolute
offset in the reproduced baseline cancels out.

Each ablation isolates ONE component, holding everything else at baseline:

  Baseline : full EVAonline (fusion + climatological Kalman)
  A1 : Stage-1 radiation fusion off  (R_s from Open-Meteo only, no CERES weight)
  A2 : R_s daily variability         (R_s replaced by its monthly climatology)
  A3 : climatological bias correction off  (priors/bounds kept; no bias subtract)
  A4 : adaptive outlier rejection off      (no p01/p99 R-inflation)
  A5 : dynamic process-noise (Q) off       (static Q, no innovation inflation)

Outputs: ablation.csv, ablation.tex
Run:     python -m validation.ablation
"""

from __future__ import annotations

import numpy as np
import pandas as pd

from validation import config
from validation import metrics as M
from validation import pipeline as P


def _eto_with_rs_climatology(cd: P.CityData) -> np.ndarray:
    """A2: replace daily fused R_s by its calendar-month climatological mean."""
    fused = P.fuse_variables(cd.nasa, cd.om, P.BASELINE_WEIGHTS)
    month = pd.to_datetime(fused["date"]).dt.month
    clim = fused.groupby(month)["ALLSKY_SFC_SW_DWN"].transform("mean")
    fused = fused.assign(ALLSKY_SFC_SW_DWN=clim.values)
    eto_raw = P.calc_eto(fused, cd.lat, cd.elev)
    if cd.priors is None:
        return eto_raw
    return P.apply_kalman_eto(eto_raw, cd.dates, cd.priors, P.BASELINE_KALMAN)


def _run_config(cd: P.CityData, name: str) -> np.ndarray:
    if name == "baseline":
        return P.run_pipeline(cd, P.BASELINE_WEIGHTS, P.BASELINE_KALMAN)
    if name == "A1":  # Stage-1 radiation fusion off -> R_s from Open-Meteo only
        w = {**P.BASELINE_WEIGHTS, "ALLSKY_SFC_SW_DWN": 0.0}
        return P.run_pipeline(cd, w, P.BASELINE_KALMAN)
    if name == "A2":  # R_s replaced by monthly climatology
        return _eto_with_rs_climatology(cd)
    if name == "A3":  # climatological bias correction off (bounds/Q kept)
        return P.run_pipeline(cd, P.BASELINE_WEIGHTS, P.BASELINE_KALMAN,
                              use_bias=False)
    if name == "A4":  # adaptive outlier rejection off (no p01/p99 R-inflation)
        return P.run_pipeline(cd, P.BASELINE_WEIGHTS, P.BASELINE_KALMAN,
                              use_bounds=False)
    if name == "A5":  # dynamic process-noise (Q) off
        kk = {**P.BASELINE_KALMAN, "q_inflation": 1.0}
        return P.run_pipeline(cd, P.BASELINE_WEIGHTS, kk)
    raise ValueError(name)


CONFIGS = [
    ("baseline", "Baseline (full EVAonline)"),
    ("A1", "A1: $R_s$ from Open-Meteo only (no CERES weight)"),
    ("A2", "A2: $R_s$ replaced by climatology"),
    ("A3", "A3: no climatological bias correction"),
    ("A4", "A4: no adaptive outlier rejection"),
    ("A5", "A5: no dynamic $Q$ adaptation"),
]


def main() -> None:
    out = config.ensure_outputs()
    cities = P.load_cities()
    print(f"Loaded {len(cities)} sites. Running {len(CONFIGS)} configurations...")

    rows = []
    site_kge: dict[str, list[float]] = {}
    for key, label in CONFIGS:
        kges, pbias = [], []
        for cd in cities.values():
            eto = _run_config(cd, key)
            kges.append(M.kge(eto, cd.ref_eto))
            pbias.append(M.pbias(eto, cd.ref_eto))
        site_kge[key] = kges
        rows.append({"key": key, "label": label,
                     "kge": float(np.mean(kges)), "pbias": float(np.mean(pbias))})
        print(f"  {label:<38s} KGE={np.mean(kges):.3f}  PBIAS={np.mean(pbias):+.2f}%")

    df = pd.DataFrame(rows).set_index("key")
    base_kge, base_pbias = df.loc["baseline", "kge"], df.loc["baseline", "pbias"]
    df["delta_kge"] = df["kge"] - base_kge
    df["delta_pbias"] = df["pbias"] - base_pbias
    df.round(4).to_csv(out / "ablation.csv")

    # LaTeX table body
    lines = ["% Auto-generated by validation/ablation.py"]
    for key, label in CONFIGS:
        r = df.loc[key]
        dk = "--" if key == "baseline" else f"{r['delta_kge']:+.3f}"
        dp = "--" if key == "baseline" else f"{r['delta_pbias']:+.2f}"
        lines.append(
            f"{label} & {r['kge']:.3f} & {r['pbias']:+.2f} & {dk} & {dp} \\\\"
        )
    (out / "ablation.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    most = df.drop("baseline")["delta_kge"].idxmin()
    print(f"\nMost influential component: {most} "
          f"(dKGE={df.loc[most, 'delta_kge']:+.3f})")
    print(f"Artefacts written to {out}")


if __name__ == "__main__":
    main()
