"""Reviewer 1, comment 1: independent calibration vs. validation.

Demonstrates that the fusion weights generalise out-of-sample under two
independent protocols, with *real recalibration* (weights are re-optimised by
minimising ET0 MAE on the training fold only -- never on the test fold):

  In-sample        : calibrate on all sites/all years; evaluate on the same.
  Temporal split   : calibrate on 1991-2010; evaluate on held-out 2011-2020.
  LOSO             : calibrate on 16 sites; evaluate on the held-out site
                     (repeated 17x).

Stage-1 weights for the six ET0-relevant variables are optimised with L-BFGS-B
in [0, 1]. The held-out evaluation always runs the FULL pipeline (fusion with
the calibrated weights + climatological Kalman), so reported metrics reflect
true generalisation.

Outputs: r1c1_cv_independent.csv, r1c1_calibrated_weights.json, r1c1_cv.tex
Run:     python -m validation.r1c1_cross_validation
"""

from __future__ import annotations

import json

import numpy as np
import pandas as pd
from scipy.optimize import minimize

from validation import config
from validation import metrics as M
from validation import pipeline as P

# Only these six weights affect ET0 (precip is not a PM input).
CAL_VARS = P.ETO_VARS
X0 = np.array([P.BASELINE_WEIGHTS[v] for v in CAL_VARS])
BOUNDS = [(0.0, 1.0)] * len(CAL_VARS)


def _year_mask(cd: P.CityData, lo: int, hi: int) -> np.ndarray:
    y = cd.dates.dt.year.values
    return (y >= lo) & (y <= hi)


def _weights_from_vec(x: np.ndarray) -> dict[str, float]:
    w = {v: float(val) for v, val in zip(CAL_VARS, x)}
    w["PRECTOTCORR"] = 0.5
    return w


def _train_mae(x: np.ndarray, cities, masks) -> float:
    """Mean over training sites of raw-fused-ET0 MAE vs Xavier (no Kalman)."""
    weights = _weights_from_vec(x)
    errs = []
    for cd in cities:
        m = masks[cd.city]
        fused = P.fuse_variables(cd.nasa, cd.om, weights)
        eto = P.calc_eto(fused, cd.lat, cd.elev)
        errs.append(M.mae(eto[m], cd.ref_eto[m]))
    return float(np.mean(errs))


def calibrate(cities, masks) -> dict[str, float]:
    res = minimize(_train_mae, X0, args=(cities, masks), method="L-BFGS-B",
                   bounds=BOUNDS, options={"maxiter": 200, "ftol": 1e-7})
    return _weights_from_vec(res.x)


def _evaluate(cd: P.CityData, weights, mask=None) -> dict[str, float]:
    eto = P.run_pipeline(cd, weights, P.BASELINE_KALMAN)
    sim, obs = (eto, cd.ref_eto) if mask is None else (eto[mask], cd.ref_eto[mask])
    return M.all_metrics(sim, obs)


def _summarise(per_site: list[dict]) -> dict[str, float]:
    df = pd.DataFrame(per_site)
    out = {}
    for k in ["r2", "kge", "nse", "mae", "rmse"]:
        out[f"{k}_mean"] = df[k].mean()
        out[f"{k}_std"] = df[k].std()
    return out


def main() -> None:
    out = config.ensure_outputs()
    cities = list(P.load_cities().values())
    print(f"Loaded {len(cities)} sites.\n")

    full = {cd.city: np.ones(len(cd.dates), bool) for cd in cities}
    calib = {cd.city: _year_mask(cd, *config.CALIB_YEARS) for cd in cities}
    valid = {cd.city: _year_mask(cd, *config.VALID_YEARS) for cd in cities}

    results, weights_log = {}, {}

    # 1) In-sample -----------------------------------------------------------
    print("[1/3] In-sample: calibrate on all, evaluate on all...")
    w_in = calibrate(cities, full)
    weights_log["in_sample"] = w_in
    results["In-sample (1991-2020)"] = _summarise(
        [_evaluate(cd, w_in) for cd in cities])

    # 2) Temporal split ------------------------------------------------------
    print("[2/3] Temporal split: calibrate 1991-2010, test 2011-2020...")
    w_tmp = calibrate(cities, calib)
    weights_log["temporal_train_1991_2010"] = w_tmp
    results["Temporal split (test 2011-2020)"] = _summarise(
        [_evaluate(cd, w_tmp, valid[cd.city]) for cd in cities])

    # 3) LOSO ----------------------------------------------------------------
    print("[3/3] Leave-one-site-out (17 folds)...")
    loso_sites = []
    for held in cities:
        train = [cd for cd in cities if cd.city != held.city]
        w = calibrate(train, {cd.city: full[cd.city] for cd in train})
        loso_sites.append(_evaluate(held, w))
        print(f"   fold {held.city:<28s} KGE={loso_sites[-1]['kge']:.3f}")
    results["LOSO (17 hold-out folds)"] = _summarise(loso_sites)

    # Write artefacts --------------------------------------------------------
    df = pd.DataFrame(results).T
    df.round(4).to_csv(out / "r1c1_cv_independent.csv")
    (out / "r1c1_calibrated_weights.json").write_text(
        json.dumps(weights_log, indent=2), encoding="utf-8")

    def cell(scheme, k):
        return f"{df.loc[scheme, k+'_mean']:.3f}$\\pm${df.loc[scheme, k+'_std']:.3f}"

    lines = ["% Auto-generated by validation/r1c1_cross_validation.py"]
    for scheme in results:
        lines.append(
            f"{scheme} & {cell(scheme,'r2')} & {cell(scheme,'kge')} & "
            f"{cell(scheme,'nse')} & {df.loc[scheme,'mae_mean']:.3f} & "
            f"{df.loc[scheme,'rmse_mean']:.3f} \\\\")
    (out / "r1c1_cv.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    print("\n" + "=" * 64)
    print(df[["kge_mean", "kge_std", "nse_mean", "mae_mean"]].round(3).to_string())
    d = df.loc["In-sample (1991-2020)", "kge_mean"] - df.loc["LOSO (17 hold-out folds)", "kge_mean"]
    print(f"\nKGE drop in-sample -> LOSO: {d:+.3f} "
          f"({'generalises well' if abs(d) < 0.05 else 'check'})")
    print(f"Artefacts written to {out}")


if __name__ == "__main__":
    main()
