"""Reviewer 1, comment 2 (+ comment 8): site-wise performance metrics.

Computes every metric *per site first*, then summarises the 17 site-wise
values with median, IQR and min-max (the aggregation the reviewer asked for).
MAE/RMSE are additionally reported as the 17-site mean (they are linear in the
observations and admit a meaningful average).

Outputs (in validation/outputs/):
  - r1c2_sitewise_metrics.csv   : one row per site (the raw 17 values)
  - r1c2_sitewise_summary.csv   : median/IQR/min/max/mean per metric
  - r1c2_table12.tex            : ready-to-paste LaTeX body for Table 12

Run:  python -m validation.r1c2_sitewise
"""

from __future__ import annotations

import pandas as pd

from validation import config
from validation.data_loader import load_paired
from validation.metrics import all_metrics

# Metrics summarised with median/IQR (interpretable per time series) vs. those
# reported as the site mean (linear -> averageable).
DISTRIBUTIONAL = ["r2", "kge", "nse"]
MEAN_ONLY = ["mae", "rmse"]


def compute_sitewise() -> pd.DataFrame:
    paired = load_paired()
    rows = []
    for city, g in paired.groupby("city"):
        m = all_metrics(g["sim"].values, g["obs"].values)
        m["city"] = city
        m["n_days"] = len(g)
        rows.append(m)
    df = pd.DataFrame(rows).set_index("city").sort_index()
    return df


def summarise(df: pd.DataFrame) -> pd.DataFrame:
    out = {}
    for col in DISTRIBUTIONAL + MEAN_ONLY + ["pbias"]:
        s = df[col]
        out[col] = {
            "median": s.median(),
            "q1": s.quantile(0.25),
            "q3": s.quantile(0.75),
            "min": s.min(),
            "max": s.max(),
            "mean": s.mean(),
        }
    return pd.DataFrame(out).T


def _fmt(v: float) -> str:
    return f"{v:.2f}"


def to_latex(summary: pd.DataFrame, n_obs: int) -> str:
    """Build the EVAonline Fusion row + a notes block for Table 12."""
    def cell(metric: str) -> str:
        r = summary.loc[metric]
        return (
            f"{_fmt(r['median'])} ({_fmt(r['q1'])},{_fmt(r['q3'])}) "
            f"[{_fmt(r['min'])},{_fmt(r['max'])}]"
        )

    fusion = (
        "\\textbf{EVAonline Fusion} & "
        f"\\textbf{{{cell('r2')}}} & "
        f"\\textbf{{{cell('kge')}}} & "
        f"\\textbf{{{cell('nse')}}} & "
        f"\\textbf{{{_fmt(summary.loc['mae', 'mean'])}}} & "
        f"\\textbf{{{_fmt(summary.loc['rmse', 'mean'])}}} \\\\"
    )
    notes = (
        "% Auto-generated by validation/r1c2_sitewise.py -- do not edit by hand.\n"
        f"% N_obs = {n_obs:,} daily observations (17 sites x 10,958 days).\n"
        "% Metrics computed per site, then summarised as median (IQR) [min,max];\n"
        "% MAE/RMSE reported as the 17-site mean.\n"
    )
    return notes + fusion + "\n"


def main() -> None:
    out = config.ensure_outputs()
    sitewise = compute_sitewise()
    summary = summarise(sitewise)

    sitewise.round(4).to_csv(out / "r1c2_sitewise_metrics.csv")
    summary.round(4).to_csv(out / "r1c2_sitewise_summary.csv")
    (out / "r1c2_table12.tex").write_text(
        to_latex(summary, config.N_OBS), encoding="utf-8"
    )

    n_obs = int(sitewise["n_days"].sum())
    print(f"Sites: {len(sitewise)} | total observations: {n_obs:,}")
    assert n_obs == config.N_OBS, (
        f"observation count {n_obs:,} != canonical {config.N_OBS:,}"
    )
    print("\nSite-wise summary (median / IQR / min-max / mean):")
    print(summary.round(3).to_string())
    worst = sitewise["kge"].idxmin()
    print(f"\nLowest-KGE site: {worst} (KGE={sitewise.loc[worst, 'kge']:.3f})")
    print(f"\nArtefacts written to {out}")


if __name__ == "__main__":
    main()
